version: "2"

services:
    app:
        build: app
        ports:
            - "8080:8080"
        logging:
            driver: "json-file"
            options:
                max-size: 1m
                max-file: 2
    api:
        build: api
        ports:
            - "1337:1337"
        logging:
            driver: "json-file"
            options:
                max-size: 1m
                max-file: 2
